apiVersion: application.jlasut.io/v1alpha1
kind: DemoBackend
metadata:
  namespace: default
  name: demo-backend
spec:
  providerConfigName: provider-example
  deletionPolicy: Delete
  backend:
    image: 'ttl.sh/axum_demo_todo:6h'
    port: 8080
    hostname: demobackend.127.0.0.1.nip.io
  database:
    postgresParameters:
      name: demo-postgres
      region: europe-central2
      network: <vpc-network>
      externalSecret: postgres-password
    databaseSchemas:
    - name: todos-schema
      sql: |
        create table todos (
          id SERIAL PRIMARY KEY,
          note VARCHAR(255) NOT NULL,
          status BOOLEAN NOT NULL DEFAULT false,
        );
  secrets: 
    secretStoreName: external-secret-store
    externalSecrets:
    - fromSecret: external-secret
      toSecret: local-secret
      version: latest
